name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for submitting this issue! We will take care of it as fast as we can.'
        pr-message: 'Thanks for submitting this pull request! We will review it shortly.'
